### ISSUE TITLE
[Official Website] Typo in example page

### ISSUE THREAD

**Issue by shadowsheep1** [reduxkotlin/ReadingListSampleApp#3]
![image](https://user-images.githubusercontent.com/16268789/68836711-3f5e0a00-06bb-11ea-9e51-d9a691e25f6e.png)

![image](https://user-images.githubusercontent.com/16268789/68836903-aed3f980-06bb-11ea-8a27-77a3ec8b2499.png)

**Comment by patjackson52** [comment]
Thanks!  Fixed in this PR https://github.com/reduxkotlin/redux-kotlin/pull/35
